clone_depth: 5

environment:
  matrix:
    - JOB: Visual Studio 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015"
    - JOB: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

build_script:
  - mkdir build && cd build
  - cmake .. -Wno-dev -G"%CMAKE_GENERATOR%"
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% -V
